// <auto-generated />
namespace Online_Appointment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migrationl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrationl));
        
        string IMigrationMetadata.Id
        {
            get { return "202205091640106_migrationl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
